version: '3.3'
services:

  home.postgres:
    image: postgres:latest
    container_name: home.postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 7654:5432
    volumes:
      - "$HOME/docker/home/postgres:/var/lib/postgresql/data"
      - "$HOME/docker/home/log:/var/log/postgres"
      - "./config/db/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
      - "./config/db/postgres/postgresql.conf:/postgresql.conf"
    networks:
      default:
        aliases:
          - home.postgres

volumes:
  esdata1:
    driver: local
